import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  reviewPrimersSidebar: [{ type: 'autogenerated', dirName: 'review-primers' }],
};

export default sidebars;
