import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  reviewPrimersSidebar: [{ type: 'autogenerated', dirName: 'review-primers' }],
  bookSidebar: [{ type: 'autogenerated', dirName: 'ic-book' }],
};

export default sidebars;
