import {
  API_GATEWAY,
  CANISTER_ID_BACKEND,
  DERIVATION_ORIGIN,
  DFX_NETWORK,
  IDENTITY_PROVIDER,
  IS_MAINNET,
} from './environment.common';

export const ENV = {
  API_GATEWAY,
  CANISTER_ID_BACKEND,
  DFX_NETWORK,
  IDENTITY_PROVIDER,
  IS_MAINNET,
  DERIVATION_ORIGIN,
};
