name: Setup NodeJS
description: Setup NodeJS

runs:
  using: 'composite'
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'
