name: Setup NodeJS
description: Setup NodeJS

runs:
  using: 'composite'
  steps:
    - name: Setup Turbo cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: false

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
