[workspace]
resolver = "2"
members = ["src/backend/api", "src/backend/impl"]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false

[workspace.dependencies]
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
candid = "0.10"
serde = "1.0"
