packages:
  - lib/angular-ui
  - lib/backend
  - lib/nns-utils
  - lib/styles
  - lib/ui
  - lib/utils
  - src/backend/integration
  - src/backend/logs
  - src/docs
  - src/frontend
  - src/marketing
  - src/nns-testing
