[package]
name = "external_canisters"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk.workspace = true
ic-nns-governance.workspace = true

candid.workspace = true
serde.workspace = true
serde_bytes.workspace = true
