[package]
name = "backend_impl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
backend_api = { path = "../api" }
ic-cdk.workspace = true
candid.workspace = true
ic-cdk-macros.workspace = true
