// Generated by Wrangler by running `wrangler types`

interface Env {
  METADATA: KVNamespace;
  BACKEND_CANISTER_ID: 'nijcm-2qaaa-aaaal-qcx2a-cai';
  /**
   * Must be set in the `.dev.vars` file if developing locally and in the Cloudflare Workers Secrets for production.
   *
   * The format must be a valid PEM string obtained generated by the `dfx` command line. A valid PEM string value for this secrets looks like this:
   *
   * ```text
   * -----BEGIN PRIVATE KEY-----
   * MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCjI6YX3x7D8oM5jH9
   * ...
   * -----END PRIVATE KEY-----
   * ```
   */
  IDENTITY_PEM: string;
  /**
   * Must be set in the `.dev.vars` file if developing locally and in the Cloudflare Workers secrets for production.
   *
   * Must be **without** the trailing slash.
   *
   * Example: `https://<your-subdomain>.grafana.net`
   */
  LOKI_ENDPOINT: string;
  /**
   * Must be set in the `.dev.vars` file if developing locally and in the Cloudflare Workers secrets for production.
   */
  LOKI_USERNAME: string;
  /**
   * Must be set in the `.dev.vars` file if developing locally and in the Cloudflare Workers secrets for production.
   */
  LOKI_PASSWORD: string;
}
