name: Build & test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-pnpm

      - uses: ./.github/actions/setup-bun

      - uses: ./.github/actions/setup-dfx

      - name: Create marketing env file
        run: |
          touch ./src/marketing/.env
          echo STORYBLOK_TOKEN=${{ secrets.STAGING_STORYBLOK_TOKEN }} >> ./src/marketing/.env

      - name: Start DFX
        run: dfx start --background

      - name: Create canisters
        run: dfx canister create --all

      - name: Build
        run: dfx build

      - name: Run frontend tests
        run: pnpm -F frontend test:ci

      - name: Canister unit tests
        run: cargo test

      - name: Canister integration tests
        run: |
          pnpm -F @cg/backend build
          pnpm -F backend-integration test
