name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: ./.github/actions/setup-rust
        with:
          cache-key: 'build-wasm'

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-env-files
        with:
          storyblok-token: ${{ secrets.STAGING_STORYBLOK_TOKEN }}

      - uses: ./.github/actions/setup-bun

      - uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build --check

      - name: Turbo test
        run: pnpm test
