name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-env-files
        with:
          storyblok-token: ${{ secrets.STAGING_STORYBLOK_TOKEN }}

      - uses: ./.github/actions/setup-bun

      - uses: ./.github/actions/setup-dfx

      - name: DFX build
        run: dfx build --check

      - name: Backend integration tests
        run: ./scripts/run-integration-tests.sh

      # - name: Backend integration tests 2
      #   run: ./scripts/run-integration-tests-2.sh

      - name: Frontend unit tests
        run: pnpm -F frontend test

      - name: UI library unit tests
        run: pnpm -F @cg/angular-ui test
