name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-pnpm

      - name: Check TypeScript Formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

      - name: Run Clippy
        run: cargo clippy
