name: Mainnet deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: mainnet
      url: https://npiey-xiaaa-aaaal-qcx2q-cai.icp0.io
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/setup-pnpm

      - uses: ./.github/actions/setup-dfx

      - name: Import DFX identity
        run: |
          echo "${{ secrets.MAINNET_PEM }}" > ./mainnet.pem
          dfx identity import --ic --storage-mode plaintext mainnet ./mainnet.pem
          dfx identity use mainnet

      - name: Create marketing env file
        run: |
          touch ./src/marketing/.env
          echo STORYBLOK_TOKEN=${{ secrets.PRODUCTION_STORYBLOK_TOKEN }} >> ./src/marketing/.env

      - name: Deploy to mainnet
        run: dfx deploy --ic
