name: Mainnet deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: mainnet
      url: https://npiey-xiaaa-aaaal-qcx2q-cai.icp0.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node

      - name: Setup environment files
        uses: ./.github/actions/setup-env-files
        with:
          storyblok-token: ${{ secrets.PRODUCTION_STORYBLOK_TOKEN }}

      - name: Setup DFX
        uses: ./.github/actions/setup-dfx

      - name: Import DFX identity
        run: |
          echo "${{ secrets.MAINNET_PEM }}" > ./mainnet.pem
          dfx identity import --ic --storage-mode plaintext mainnet ./mainnet.pem
          dfx identity use mainnet

      - name: Deploy to mainnet
        run: dfx deploy --ic
