name: TypeScript tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typescript_tests:
    name: TypeScript tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Check TypeScript Formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint
